name: flutter_streetview_web
description: A Flutter package for Google Street View integration with customizable markers.
version: 1.0.1
homepage: https://pub.dev/packages/flutter_streetview_web
repository: https://github.com/anilaydinaa/flutter_streetview_web
issue_tracker: https://github.com/anilaydinaa/flutter_streetview_web/issues
documentation: https://pub.dev/documentation/flutter_streetview_web/latest/
license: MIT

environment:
  sdk: ^3.8.1
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/street_view_web_view.html
